HPCC-27713 - Create confidence test and key file for the Learning Trees bundle
hpcc-systems/LearningTrees pull request #12
Opened 2022-06-02 17:15 UTC by NSel1727

- Create ecl and key folder
- Use modified existing test code to create a confidence test for the Learning Trees bundle with version control
- Create a key file

2022-06-06 15:35 UTC, AttilaVamos requested changes
Overall seems ok, but there are some comments.
The 'ecl/key/ClassificationTestModified.txt' file is empty and it has wrong extension.

2022-06-06 15:35 UTC, AttilaVamos commented on ecl/ClassificationTestModified.ecl
> +	Ind1 := PROJECT(trainNF(number != 52 AND id <= maxRecs), TRANSFORM(NumericField,
We need to avoid the magic numbers like '52'. Please name it (store it a self documenting variable/constant).

2022-06-06 15:35 UTC, AttilaVamos commented on ecl/ClassificationTestModified.ecl
> +	Dep1 := PROJECT(trainNF(number = 52 AND id <= maxRecs), TRANSFORM(DiscreteField,
Same as above (and for any existing further occurrences).

2022-06-06 15:35 UTC, AttilaVamos commented on ecl/RegressionTestModified.ecl
> +					SELF.number := IF(nonSequentialIds, (5*LEFT.number -1), LEFT.number -1),
Wrong indentations, please change.

2022-06-10 15:08 UTC, AttilaVamos commented on ecl/key/ClassificationTestModified.xml
> +
Please remove this empty line, but keep '\n' at the end of last line

2022-06-10 15:08 UTC, AttilaVamos commented on ecl/key/RegressionTestModified.xml
> +
Please remove this empty line, but keep '\n' at the end of last line

2022-06-10 15:44 UTC, AttilaVamos commented on ecl/key/ClassificationTestModified.xml
> +<Result>
Please remove all '<Result>\n' and </Result>\n' lines from both key file as well.

2022-06-13 17:34 UTC, NSel1727 commented
@AttilaVamos @ghalliday Please review my pull request.

2022-06-14 09:23 UTC, ghalliday approved these changes
I didn't spot anything (I didn't check the code for accuracy!)

2022-06-20 16:07 UTC, NSel1727 commented
@AttilaVamos Please review a final time.

2022-06-22 14:40 UTC, AttilaVamos approved these changes
I think it is ready to merge.

2022-06-22 14:40 UTC, AttilaVamos commented
@ghalliday please merge this PR.

2022-06-28 13:34 UTC, merged